### ISSUE TITLE
Error in cogs

### ISSUE THREAD

**Issue by takipsizad** [top-gg/python-sdk#52]
This issue tracker is **ONLY** used for reporting bugs with __topggpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior

Should work fine
## Current Behavior
Error

`  File "C:\Users\pc\python\lib\site-packages\discord\ext\commands\bot.py", line 644, in _load_from_module_spec
    setup(self)
  File "c:\Users\pc\projeler\bot\cogs\redditcommands.py", line 63, in setup
    bot.add_cog(Redditcommands(bot))
  File "c:\Users\pc\projeler\bot\cogs\redditcommands.py", line 12, in __init__
    self.dbl = topgg.DBLClient(bot=self.bot, token=dbltoken)
  File "C:\Users\pc\python\lib\site-packages\topgg\client.py", line 112, in __init__
    self.http = HTTPClient(token, loop=self.loop, session=kwargs.get("session"))
  File "C:\Users\pc\python\lib\site-packages\topgg\http.py", line 83, in __init__
    self.rate_limiter = AsyncRateLimiter(
  File "C:\Users\pc\python\lib\site-packages\topgg\ratelimiter.py", line 53, in __init__
    self.__lock = asyncio.Lock()
  File "C:\Users\pc\python\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\pc\python\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pc\projeler\bot\bot.py", line 61, in <module>
    bot.load_extension(f"cogs.{name}")
  File "C:\Users\pc\python\lib\site-packages\discord\ext\commands\bot.py", line 704, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\pc\python\lib\site-packages\discord\ext\commands\bot.py", line 649, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.redditcommands' raised an error: RuntimeError: There is no current event loop in thread 'MainThread'.`
## Development Environment

3.9 ,1.0.1
## Steps to Reproduce

1.Using top gg client in cog

## Context

Votelocking command

**Comment by norinorin** [comment]
Odd, I don't think this should happen. Did you by any chance call `asyncio.run` or something that closes the event loop?

**Comment by shivaco** [comment]
Is there any update on this?
